FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
# Use npm install --production to avoid requiring a package-lock.json
RUN npm install --production
COPY . .
EXPOSE 8080
CMD ["node", "index.js"]
